version: '2.2'
services:

    backend:
        build:
            context: .
            dockerfile: api/Dockerfile
        container_name: follow-beers-api
        volumes:
            - ./api/src:/usr/src/app/src
        restart: always
        ports:
            - "4000:4000"
        networks:
            - internal


    frontend:
        build:
            context: .
            dockerfile: front/Dockerfile
        container_name: follow-beers-front
        volumes:
            - ./front/src:/home/node/app/src
        restart: always
        stdin_open: true
        command:  npm run start
        ports:
            - "80:3000"
        networks:
            - internal

networks:
    internal:
        driver: bridge
